### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by upascal** [spatstat/spatstat.sphere#3]
I'm interested in this package but I am having trouble installing it on a mac because of an issue with rpanel. I saw someone else had a similar issue in 2017. Is there a mac binary for the latest version of the package? Thanks

**Comment by rubak** [comment]
This package under development is a bit outdated, but you are very welcome to give it a try. We don't have binaries for mac, and can't easily provide them. The problem is that the dependency `s2` has been completely rewritten and published to CRAN in an incompatible version. You need to first install `s2` from `spatstat/s2`, which should happen automatically if you install via `remotes::install_github("spastat/spatstat.sphere")`. You also need `spatstat.gui` and this is where you encounter the problem with rpanel on mac. I have tried to enable `spatstat.gui` on <https://spatstat.r-universe.dev/> so you may be lucky that you can download a working binary for mac there in a day or so. Once you have a working `spatstat.gui` it should work to install this via `remotes`. Let me know how it goes.

**Comment by rubak** [comment]
I have now removed the dependency on `spatstat.gui`, so it should be much easier to install from source. Main obstacle will be to get the right version of `s2` installed. Please check that this works for you @upascal and close the issue.

**Comment by upascal** [comment]
Thank you so much! I was able to download it without issues and plot a s2pp pattern.
